
<!DOCTYPE html>
<html lang="en">

<head>
    <title>PHP homework</title>
    <meta name="keywords" content=" jacob, web development homework">
    <meta name="Author:" value="Jacob Scroggins">
    <meta name="destription" content="homework ">
    <meta charset="UTF-8">
    <meta name="viewprt" content="width=device-width, initial-scale=1.0">

    <?php

    $yourName = "Jacob";

    ?>
    <style>

    </style>

    <script>
    
    </script>

</head>

<body >
    <header>
       <?php echo "<h1>  3-1: PHP Basics </h1>" ?>
    </header>

    
   
</body>

</html>